### ISSUE TITLE
Undefined variable $key in request.class.php:438

### ISSUE THREAD

**Issue by Endijs** [clusterpoint/php-client-api#1]
There is undefined variable $key in file request.class.php line 438
`throw new CPS_Exception(array(array('long_message' => 'Invalid UTF-8 encoding in key = \''.$key.'\'', 'code' => ERROR_CODE_INVALID_UTF8, 'level' => 'ERROR', 'source' => 'CPS_API')));`
https://github.com/clusterpoint/php-client-api/blob/master/request.class.php#L438

**Comment by NorchaCP** [comment]
Error message changed to "Invalid UTF-8 encoding in document ID"
