### ISSUE TITLE
examples/search-geo_example.php uses functions and methods from php-client-api_ns

### ISSUE THREAD

**Issue by Endijs** [clusterpoint/php-client-api#2]
There is problem with examples/search-geo_example.php. It uses functions and methods which are not in php-client-api library (they are in php-client-api_ns). 

For example:
- Line 29: `CPS_CircleDefinition`
- Line 32: `CPS_PolygonDefinition`
- Lines 60 and 61: `$searchRequest->setShape()`
- Also - line 35 `$shapes` gets defined, but is not used.

**Comment by NorchaCP** [comment]
Added GEO search helper functions in php-client-api library.
